### ISSUE TITLE
Encumbrance tries to count abilities towards weight 

### ISSUE THREAD

**Issue by vonubelmann** [eegag/slot-based-encumbrance#1]
On the character sheet, for the Abilities tab, the module is trying to count Abilities on there towards slots and it displays a "NaN" message in at the bottom of the inventory tab.
![Abilities](https://user-images.githubusercontent.com/117138497/199156134-44c7ea40-20e2-4619-83ea-cbf0ef5ed704.jpg)

**Comment by eegag** [comment]
Good catch. I'm honestly not sure if this is new or if I just never saw the behavior before. Regardless, I fixed the code to ignore both spell and ability item types when totaling up inventory slots.
