### ISSUE TITLE
Removes spell tab.

### ISSUE THREAD

**Issue by vonubelmann** [eegag/slot-based-encumbrance#2]
Enabling this module removes the Spell tab on the character sheet.

![image](https://user-images.githubusercontent.com/117138497/199299043-2c43fc7f-d411-48ee-ba14-2d4cb74b7950.png)

**Comment by eegag** [comment]
I thought I pushed this fix in 0.3.4 as well, but I guess not :). Thanks for pointing it out. v0.3.5 fixes the issue.
