### ISSUE TITLE
Module prevents movement calculation in character sheet

### ISSUE THREAD

**Issue by vonubelmann** [eegag/slot-based-encumbrance#3]
When enabled, the module prevents movement from being calculated on the character sheet.

When the Calculate Movement box is unchecked, the derivative movement boxes do not fill in.

![image](https://user-images.githubusercontent.com/117138497/199352068-204bc5fa-a3ca-43ae-bae7-dd216156d389.png)

**Comment by eegag** [comment]
Haha, I have no idea what this checkbox actually does. I have never clicked it. I am out of town but I will fix it when I return.

**Comment by eegag** [comment]
I am unable to reproduce this error. Validated with and without armor. The calculation works whether the checkbox is checked or not (I could probably remove it as a part of the module, movement calc in inherent to how the module works).

@vonubelmann is your test actor Glen Copperridge holding more that 2 hands worth of weapons and gear? If they try to hold too much, the movement will get set to 0 until it's fixed.

![image](https://user-images.githubusercontent.com/111909085/200834324-de9e275a-43d6-401f-b995-8afb800b7a41.png)

**Comment by vonubelmann** [comment]
Sorry it took me a bit to reply. I think that was it, they had a Holy Symbol equipped.
