### ISSUE TITLE
Slots/Weight - non-integer

### ISSUE THREAD

**Issue by dczwardCZAR** [eegag/slot-based-encumbrance#4]
I'm having trouble making non weapon or armor items have less than 1 for slots/weight. I'd like to make some items 1/2 slot, or 1/4, with .5 or .25. However, entering those values doesn't see to change the encumbrance bar in any way.

**Comment by eegag** [comment]
You would still set the slot value as 1, but then use the quantity and max values.

For example, something that you can fit 4 to a slot (or, .25 slots per individual item) would have a max of 4 and a slot value of 1. Then it will automatically calculate your total slots based on your current quantity. So if you had 1-4 items, it would be 1 slot. 5-8 items would take up 2 slots, etc.

**Comment by dczwardCZAR** [comment]
That's OK, but if I wanted a tinder box to be 1/2 slot, and I have only 1 of them. I would expect that entering Slots: .5 would work. However, currently, entering Slots: 0.5 , it is still taking up 1 slot...

<img width="520" alt="tinderb" src="https://user-images.githubusercontent.com/91574640/214724052-3fe9e588-0292-4004-987d-44457bb24c64.png">

By comparison, I can do this to armor or weapon types. For example, on a dagger, near the "weight" icon, I can enter ".5" and it only takes up 1/2 slot...

<img width="520" alt="dagger" src="https://user-images.githubusercontent.com/91574640/214724119-6561eaf1-45c6-41f8-8f4c-9e632a29efa1.png">

Can we have the non weapons & armor items be adjustable in the same way?

**Comment by dczwardCZAR** [comment]
The idea is that "slots" abstractly represent both the weight of an item and how cumbersome it is (therefore, even light but unwieldy items may take up more than 1 item slot). So, I might have 9 small items that are .25 slots, for a total of 2.25 slots.

**Comment by eegag** [comment]
Ah, I see. I will check the calculations to see if I could easily enable slot sizes smaller than 1 for items.

You could set your smallest item type to 1 and multiply your other slot values (including your carrying max) by 4 or whatever. E.g. a tinder box takes up 1 slot and a sword takes up 4 slots.

**Comment by eegag** [comment]
What you want to do works already if you remove the quantity max from your items. That's why it works for weapons, because they don't have a max. When there is a quantity max, the calculation is different because the module sees those as "bundled" items.

So, for your Tinder Box, you want the Qt. field to say 1/  instead of 1/1.

**Comment by dczwardCZAR** [comment]
aha, that does it. Thank you for letting me know!

**Comment by StrictTimeRecords** [comment]
To add something on to this. Would it be possible to have items which are taking up less than a full slot show as a fraction rather than a decimal.

It is much easier on the eyes if you are using fractions like 1/3 or 1/6 to have them display as such rather than 0.333 or 0.166.

**Comment by eegag** [comment]
@StrictTimeRecords Are you asking for the bar at the bottom of the inventory tab to say something like "4 1/2 / 10" if you have 4.5 slots filled?
