### ISSUE TITLE
Could you possible expand this module to include the SWADE system?

### ISSUE THREAD

**Issue by StealthRevealed** [eegag/slot-based-encumbrance#6]
Hey Eegag!

I was reading through your module here and It is almost exactly the sort of thing I need to help me run my "Tyrnador" game using the SWADE core system in foundry.

As you are also probably the only person I've seen so far who has tried to implement a slot based encumbrance system using foundry, I was wondering if you'd be able to take a crack at forking this to function for the SWADE system?

Obviously this is simply a request from a stranger on the internet, and the only thing I have to offer for your sacrifice is my eternal gratitude. But I thought there wasn't any harm in asking! I am just dipping into coding these modules and I have very little knowledge of how difficult it would actually be to convert the functionality here over to the SWADE system.

**Comment by eegag** [comment]
Hey there, I appreciate you asking - you never know until you try! Unfortunately, I do not have the time to take this on. But, if you find someone else willing to give it a try and they have any questions about my implementation, send them my way and I will answer any questions!
